global using CommunityToolkit.Maui.Markup;
global using Microsoft.Extensions.Logging;
global using Microsoft.Maui.LifecycleEvents;
global using MonerisTest.Pages;
global using MonerisTest.Services.Implementations;
global using MonerisTest.Services.Interfaces;
global using MonerisTest.ViewModels;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using CommunityToolkit.Mvvm.Messaging;
global using Moneris;
global using MonerisTest.Models;
global using CommunityToolkit.Mvvm.Messaging.Messages;
global using System.ComponentModel.DataAnnotations;
global using CommunityToolkit.Maui.Converters;
global using static CommunityToolkit.Maui.Markup.GridRowsColumns;
global using Realms;
global using System.Collections.ObjectModel;